package no.ssb.klass.designer.editing;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

import no.ssb.klass.designer.editing.codetables.ReadOnlyCodeTable;
import no.ssb.klass.designer.editing.codetables.TranslationCodeTable;
import no.ssb.klass.designer.editing.codetables.VariantCodeTable;
import no.ssb.klass.designer.editing.codetables.levels.HierarchyToggleComponent;
import no.ssb.klass.designer.editing.codetables.levels.PrimaryLevelsComponent;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView extends LoginDesign
 * implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VariantCodeEditorDesign extends VerticalLayout {
    protected Button importButton;
    protected Button exportButton;
    protected Label primaryLanguage;
    protected HierarchyToggleComponent hierarchyToggleComponent;
    protected SelectEditLanguageOrVariantComponent selectEditLanguageOrVariant;
    protected Label variantName;
    protected PrimaryLevelsComponent variantLevels;
    protected Label originalVersionName;
    protected VariantCodeTable variantCodeTable;
    protected ReadOnlyCodeTable originalVersion;
    protected TranslationCodeTable translationCodeTable;

    public VariantCodeEditorDesign() {
        Design.read(this);
    }
}
